#!/usr/bin/env python3
"""Write the soundness grid (grid.py) to cases/ and manifest.tsv.

    python3 generate.py            # (re)write cases/ and manifest.tsv
    python3 generate.py --check    # fail if the checked-in files differ

The checked-in programs are the test inputs; regenerate only when grid.py's
operations, contexts, or model change, and review the manifest diff.
"""

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import grid  # noqa: E402

CASES = HERE / "cases"
MANIFEST = HERE / "manifest.tsv"
HEADER = "name\tkind\tcontext\top1\top2\texpect\treasons\n"


def render(case: grid.Case) -> str:
    reasons = " | ".join(case.reasons) if case.reasons else "-"
    return (f"// soundness grid case {case.name}\n"
            f"// kind={case.kind} context={case.context} op1={case.op1} op2={case.op2}\n"
            f"// expect: {case.expect}" + (f" ({reasons})" if case.reasons else "") + "\n"
            + case.source)


def expected_files():
    files = {}
    rows = [HEADER]
    for case in grid.cases():
        path = CASES / case.kind / case.context / f"{case.name}.top"
        files[path] = render(case)
        rows.append("\t".join([case.name, case.kind, case.context, case.op1,
                               case.op2, case.expect,
                               " | ".join(case.reasons) or "-"]) + "\n")
    files[MANIFEST] = "".join(rows)
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    files = expected_files()
    existing = set(CASES.rglob("*.top")) if CASES.exists() else set()
    if args.check:
        stale = [p for p, text in files.items()
                 if not p.exists() or p.read_text() != text]
        extra = existing - set(files)
        for p in stale[:10]:
            print(f"differs from grid.py: {p.relative_to(HERE)}")
        for p in sorted(extra)[:10]:
            print(f"not generated by grid.py: {p.relative_to(HERE)}")
        if stale or extra:
            print("run generate.py and review the diff")
            return 1
        print(f"{len(files) - 1} cases match grid.py")
        return 0
    for p in existing - set(files):
        p.unlink()
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"wrote {len(files) - 1} cases and manifest.tsv")
    return 0


if __name__ == "__main__":
    sys.exit(main())
