add_executable(typeinference_unit_tests
               constraints/PolyTypeConstraintCollectTest.cpp)
target_sources(
  typeinference_unit_tests
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipAlphaTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipConsTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipFunctionTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipIntTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipMuTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipRecordTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipAbsentFieldTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipRefTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipVarTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipVarSetTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TipTypeTermTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/SubstituterTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/CopierTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TypeVarsTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/TypeConstraintCollectTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/PolyTypeConstraintCollectTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/TypeConstraintTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/AbsentFieldCheckerTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TermUnionFindTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TermUnifierTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TipVarRegistryTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TipTermClosureTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TipTermBridgeTest.cpp)
target_link_libraries(
  typeinference_unit_tests
  PRIVATE antlr4_static
          ${llvm_libs}
          ast
          types
          symboltable
          frontend
          semantic
          codegen
          optimizer
          error
          test_helpers
          tipc_test_includes
          coverage_config
          Catch2::Catch2WithMain)
include(Catch)
catch_discover_tests(typeinference_unit_tests)
