add_executable(typeinference_unit_tests
               constraints/PolyTypeConstraintCollectTest.cpp)
target_sources(
  typeinference_unit_tests
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopAlphaTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopConsTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopFunctionTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopIntTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopMuTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopOwningRefTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopVarTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopVarSetTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TopTypeTermTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/SubstituterTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/CopierTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/concrete/TypeVarsTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/FunAppTypingTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/TypeConstraintCollectTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/PolyTypeConstraintCollectTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/TypeConstraintTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/constraints/TopTypeFeatureTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TermUnionFindTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TermUnifierTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TopTermClosureTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/TopTermAdapterTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/solver/UnifierTest.cpp)
target_link_libraries(
  typeinference_unit_tests
  PRIVATE antlr4_static
          ${llvm_libs}
          ast
          types
          symboltable
          frontend
          semantic
          topc_codegen
          optimizer
          error
          test_helpers
          topc_test_includes
          coverage_config
          Catch2::Catch2WithMain)
include(Catch)
catch_discover_tests(typeinference_unit_tests)
